name: Deploy integrations Service (Test) to ECS

on:
  push:
    branches: [ test ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: jesty/test-integrations-service
          IMAGE_TAG: test-integrations-service-${{ github.sha }}
        run: |
          echo "Building and pushing Docker image for TEST..."
          docker build --platform linux/arm64 \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:test-integrations-service-latest \
            .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:test-integrations-service-latest

  update-ecs:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Update ECS service (Test)
        run: |
          echo "Forcing ECS service deployment (TEST)..."
          aws ecs update-service \
            --cluster jesty-cluster \
            --service test-integrations-service \
            --force-new-deployment

      - name: Wait for ECS tasks to stabilize
        run: sleep 100


  restart-nginx:
    runs-on: ubuntu-latest
    needs: update-ecs
    steps:
      - name: Restart Nginx on EC2 Test ENV
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "Restarting Nginx..."
            sudo systemctl restart nginx
